[theme]
primaryColor = "#4267B2"
backgroundColor = "#F0F2F5"
secondaryBackgroundColor = "#E4E6EB"
textColor = "#1C1E21"
font = "sans serif"

[server]
runOnSave = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
